"""adiciona unit_price em appointment_procedures

Revision ID: 05da4f2b936d
Revises: d276705bd526
Create Date: 2026-07-30 20:29:17.421339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05da4f2b936d'
down_revision: Union[str, Sequence[str], None] = 'd276705bd526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('appointment_procedures', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
