"""Corrigido bug do model referente as colunas unicas

Revision ID: 6a91cb953d13
Revises: bef5f76b1351
Create Date: 2026-07-27 17:58:31.069546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a91cb953d13'
down_revision: Union[str, Sequence[str], None] = 'bef5f76b1351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
