"""profissao opcional

Revision ID: 7f2a89ca807a
Revises: 
Create Date: 2026-07-27 14:29:07.503339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '7f2a89ca807a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentists_cpf_hash'))
        batch_op.create_index(batch_op.f('ix_dentists_cpf_hash'), ['cpf_hash'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               nullable=False)

    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentists_cpf_hash'))
        batch_op.create_index(batch_op.f('ix_dentists_cpf_hash'), ['cpf_hash'], unique=True)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B612A7311EB'))
    )
    # ### end Alembic commands ###
