"""appointment arrumado, combinacao de valores unicos removida

Revision ID: d276705bd526
Revises: 6a91cb953d13
Create Date: 2026-07-28 18:45:44.690774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd276705bd526'
down_revision: Union[str, Sequence[str], None] = '6a91cb953d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
