"""cpf novo

Revision ID: eca203696aa8
Revises: 3557a5e1e44e
Create Date: 2026-07-14 22:04:38.349059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca203696aa8'
down_revision: Union[str, Sequence[str], None] = '3557a5e1e44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentist_schedule', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_dentist_schedule_day', ['dentist_id', 'schedule_id', 'day_of_week'])
        batch_op.create_foreign_key(None, 'schedules', ['schedule_id'], ['id'])
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('cpf_encrypted', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'FERIAS', 'AFASTADO', name='dentist_status'), server_default='ativo', nullable=False))
        batch_op.create_index(batch_op.f('ix_dentists_cpf_hash'), ['cpf_hash'], unique=True)
        batch_op.drop_column('cpf')

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_dentists_cpf_hash'))
        batch_op.drop_column('status')
        batch_op.drop_column('cpf_encrypted')
        batch_op.drop_column('cpf_hash')

    with op.batch_alter_table('dentist_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_dentist_schedule_day', type_='unique')

    # ### end Alembic commands ###
