from .user import User
from .clinic import Clinic
from .dentist import Dentist
from .appointment import Appointment
from .procedure import Procedure
from .schedule import Schedule
from .patient import Patient
from .specialty import Specialty
from .associations.dentist_specialties import dentist_specialties
from .associations.appointment_procedure import AppointmentProcedure
from .associations.dentist_schedules import DentistSchedule
from .expense import Expense
from .receivable import Receivable
